-- DML TRIGGER 
--  1. AFTER TRIGGER
--  2. INSTEAD OF TRIGGER

-- CREATE TABLE EMPLOYEEAUDIT(
--     ID INT PRIMARY KEY NOT NULL IDENTITY(1,1),
--     AUDIT_DATA NVARCHAR(100)
-- )

-- SELECT * FROM EMPLOYEEAUDIT

-- AFTER TRIGGER 
CREATE TRIGGER TR_EMPLOYEE_FORINSERT
ON EMPLOYEE 
FOR INSERT 
AS 
BEGIN
    DECLARE @ID INT
    SELECT @ID = ID FROM INSERTED 

    INSERT INTO EMPLOYEEAUDIT VALUES
    (
        'NEW EMPLOYEE WITH ID = ' + CAST(@ID AS NVARCHAR(5)) + ' IS ADDED AT '+ CAST(GETDATE() AS NVARCHAR(20))
    )
END

SELECT * FROM EMPLOYEE
SELECT * FROM EMPLOYEEAUDIT

INSERT INTO EMPLOYEE VALUES (8,'KANTI','MALE',3000,1, 2004-11-20)

INSERT INTO EMPLOYEE VALUES(8,'VED','MALE',50000,2,'2001-09-07 12:30:40.000')

CREATE TRIGGER TR_EMPLOYEE_FORDELETE
ON EMPLOYEE
FOR DELETE
AS 
BEGIN
    DECLARE @ID INT
    SELECT @ID = ID FROM DELETED 
    INSERT INTO EMPLOYEEAUDIT VALUES(
        'AN EXISTING EMPLOYEE WITH ID = '+ CAST(@ID AS NVARCHAR(5)) + ' IS DELETED AT ' + CAST(GETDATE() AS NVARCHAR(20))
    )
END

DELETE FROM EMPLOYEE WHERE ID = 8

ALTER TRIGGER TR_EMPLOYEE_FORUPDATE
ON EMPLOYEE
FOR UPDATE 
AS
BEGIN
    DECLARE @ID INT
    DECLARE @OLDNAME NVARCHAR(25) , @NEWNAME NVARCHAR(20)
    DECLARE @OLDGENDER NVARCHAR(20), @NEWGENDER NVARCHAR(20)
    DECLARE @OLDSALARY INT, @NEWSALARY INT
    DECLARE @OLDDEPARTMENT_ID INT, @NEWDEPARTMENT_ID INT 
    DECLARE @AUDITSTRING NVARCHAR(1000)

    SELECT * INTO #TEMPTABLE FROM INSERTED 
    WHILE(EXISTS(SELECT ID FROM #TEMPTABLE))
    BEGIN
        SET @AUDITSTRING = ''
        SELECT TOP 1 @ID = ID, @NEWNAME = NAME , @NEWGENDER = GENDER , @NEWSALARY = SALARY,@NEWDEPARTMENT_ID = DEPARTMENT_ID FROM #TEMPTABLE

        SELECT @OLDNAME = NAME , @OLDGENDER = GENDER , @OLDSALARY = SALARY , @OLDDEPARTMENT_ID = DEPARTMENT_ID FROM DELETED WHERE ID = @ID

        SET @AUDITSTRING = 'EMPLOYEE WITH ID = ' + CAST(@ID AS NVARCHAR(5)) + ' CHANGED'
        IF(@OLDNAME != @NEWNAME )
            SET @AUDITSTRING = @AUDITSTRING + ' NAME FROM ' + @OLDNAME + ' TO ' + @NEWNAME
        IF(@OLDGENDER <> @NEWGENDER)
            SET @AUDITSTRING = @AUDITSTRING + ' GENDER FROM ' + @OLDGENDER + ' TO ' + @NEWGENDER
        IF(@OLDSALARY != @NEWSALARY)
         SET @AUDITSTRING = @AUDITSTRING + ' SALARY FROM ' + CAST(@OLDSALARY AS NVARCHAR(6)) + ' TO ' + CAST(@NEWSALARY AS NVARCHAR(6))
        IF(@OLDDEPARTMENT_ID <> @NEWDEPARTMENT_ID)
            SET @AUDITSTRING = @AUDITSTRING + ' DEPARTMENT FROM ' + CAST(@OLDDEPARTMENT_ID AS NVARCHAR(2)) + ' TO ' +CAST(@NEWDEPARTMENT_ID AS NVARCHAR(2))
        
        INSERT INTO EMPLOYEEAUDIT VALUES(@AUDITSTRING)
        DELETE FROM #TEMPTABLE WHERE ID = @ID
    END
END

UPDATE EMPLOYEE SET SALARY = 5000 WHERE ID = 8

UPDATE EMPLOYEE SET SALARY = 5000 , NAME = 'BROS' , GENDER= 'FEMALE' WHERE ID = 8


SELECT * FROM EMPLOYEEAUDIT

DROP TABLE EMPLOYEEAUDIT