-- cursor is used when we have to visit row by row but its gonna make you slow
DECLARE @PRODUCTID INT
DECLARE @NAME VARCHAR(30)

DECLARE PRODUCTCURSOR CURSOR FOR 
SELECT ID, NAME FROM TBLPRODUCTS WHERE ID<=1000

OPEN PRODUCTCURSOR
FETCH NEXT FROM PRODUCTCURSOR INTO @PRODUCTID, @NAME

WHILE(@@FETCH_STATUS = 0)
BEGIN
    SELECT @NAME = NAME FROM TBLPRODUCTS WHERE ID = @PRODUCTID

    IF(@NAME = 'PRODUCT - 55')
    BEGIN
        UPDATE TBLPRODUCTSALE SET UNITPRICE = 55 WHERE PRODUCTID = @PRODUCTID
    END
    ELSE IF(@NAME = 'PRODUCT - 65')
    BEGIN
        UPDATE TBLPRODUCTSALE SET UNITPRICE = 65 WHERE PRODUCTID = @PRODUCTID
    END
    ELSE IF(@NAME LIKE 'PRODUCT - 100%')
    BEGIN
        UPDATE TBLPRODUCTSALE SET UNITPRICE = 1000 WHERE PRODUCTID = @PRODUCTID
    END
    FETCH NEXT FROM PRODUCTCURSOR INTO @PRODUCTID, @NAME
END

CLOSE PRODUCTCURSOR
DEALLOCATE PRODUCTCURSOR
SELECT * FROM TBLPRODUCTS
SELECT * FROM TBLPRODUCTSALE

SELECT NAME,UNITPRICE FROM TBLPRODUCTS JOIN TBLPRODUCTSALE
ON TBLPRODUCTS.ID =TBLPRODUCTSALE.PRODUCTID WHERE (NAME = 'PRODUCT - 55' OR NAME = 'PRODUCT - 65' OR NAME LIKE 'PRODUCT - 100%')

UPDATE TBLPRODUCTSALE SET UNITPRICE = CASE
                                            WHEN NAME = 'PRODUCT - 55' THEN 55
                                            WHEN NAME = 'PRODUCT - 65' THEN 65
                                            WHEN NAME LIKE 'PRODUCT - 100%' THEN 1000
                                        END
FROM TBLPRODUCTSALE JOIN TBLPRODUCTS ON TBLPRODUCTS.ID =TBLPRODUCTSALE.PRODUCTID