--TABLE A
CREATE TABLE TABLEA(
    ID INT IDENTITY PRIMARY KEY,
    NAME NVARCHAR(50)
)
INSERT INTO TABLEA VALUES('MARK')
-- INSERT INTO TABLEA VALUES('BEN')
-- INSERT INTO TABLEA VALUES('TODD')
-- INSERT INTO TABLEA VALUES('PAM')
-- INSERT INTO TABLEA VALUES('SARA')
-- TABLE B
CREATE TABLE TABLEB(
    ID INT IDENTITY PRIMARY KEY,
    NAME NVARCHAR(50)
)
INSERT INTO TABLEB VALUES('MARY')

SELECT * FROM TABLEA
SELECT * FROM TABLEB
DROP TABLE TABLEA
DROP TABLE TABLEB
--TRANSACTION 1
BEGIN TRAN
UPDATE TABLEA SET NAME = 'MARK TRANSACTION 1' WHERE ID =1

UPDATE TABLEB SET NAME = 'MARK TRANSACTION 1' WHERE ID =1
COMMIT TRAN

--TRANSACTION 2
BEGIN TRAN
UPDATE TABLEB SET NAME = 'MARY TRANSACTION 2' WHERE ID =1

-- WHEN ITS TRY TO UPDATE A TABLEA THEN IT GONE A DEADLOCK PHASE AND TRANSACTION 2 HAS CHOOSEN AS DEADLOCK VICTIMS
UPDATE TABLEA SET NAME = 'MARY TRANSACTION 2' WHERE ID =1
COMMIT TRAN

-- WHEN DEADLOCK_PRIORITY IS GIVEN BEFORE THE TRANSACTION
--TRANSACTION 1
--IF SET DEADLOCK_PRIORITY VALUE(LOW,NORMAL,HIGH) IS NOT GIVEN THEN IT CONSIDER ITS AS NORAML PRIORITY
BEGIN TRAN
UPDATE TABLEA SET NAME = 'MARK TRANSACTION 1' WHERE ID =1
-- WHEN ITS TRY TO UPDATE A TABLEA THEN IT GONE A DEADLOCK PHASE AND TRANSACTION 1 HAS CHOOSEN AS DEADLOCK VICTIMS BCZ PF TRANSACTION 2 HAVING HIGH PRIORITY
UPDATE TABLEB SET NAME = 'MARK TRANSACTION 1' WHERE ID =1
COMMIT TRAN

--TRANSACTION 2
SET DEADLOCK_PRIORITY HIGH -- HERE PRIORITY IS SET TO HIGH SO IT WILL NOT CHOOSEN AS DEADLOCK VICTIM
BEGIN TRAN
UPDATE TABLEB SET NAME = 'MARY TRANSACTION 2' WHERE ID =1


UPDATE TABLEA SET NAME = 'MARY TRANSACTION 2' WHERE ID =1
COMMIT TRAN


-- WHEN DATA IS MORE THEN WHICH WILL BE CHOOSEN AS DEADLOCK VICTIM
-- TRANSACTION 1
BEGIN TRAN
    UPDATE TABLEA SET NAME = NAME + ' TRANSACTION 1' WHERE ID IN (1,2,3,4,5)

    UPDATE TABLEB SET NAME = NAME + ' TRANSACTION 1' WHERE ID = 1
COMMIT TRAN

--TRANSACTION 2
BEGIN TRAN
    UPDATE TABLEB SET NAME = NAME + ' TRANSACTION 2' WHERE ID = 1
-- IN THIS CASE IT TRANSACTION 2 WILL CHOOSEN AS DEADLOCK VICTIM BECAUSE IT COST LESS COMPARE TO TRANSACTION 1
    UPDATE TABLEA SET NAME = NAME + ' TRANSACTION 2' WHERE ID IN (1,2,3,4,5)
COMMIT TRAN

-- LOGGING DEADLOCKS IN SQL SERVER
DBCC TRACEON(1222,1) -- HERE 1 FOR SESSION LEVEL TRACE FLAG AND -1 FOR GLOBAL LEVEL
DBCC TRACESTATUS(1222,-1) -- IT WILL GIVE STATUS WHETHER GLOBAL AND SESSION LEVEL TRACE FLAG IS ON OR OFF
DBCC TRACEOFF(1222,1) -- IT WILL OFF THE TRACE FLAG

EXECUTE sp_readerrorlog

CREATE PROC SP_TRANSACTION1
AS 
BEGIN
    BEGIN TRAN
        UPDATE TABLEA SET NAME = 'MARK TRANSACTION 1' WHERE ID =1
        WAITFOR DELAY '00:00:10'
        UPDATE TABLEB SET NAME = 'MARK TRANSACTION 1' WHERE ID =1
    COMMIT TRAN
END

EXECUTE SP_TRANSACTION1

SELECT OBJECT_NAME([OBJECT_ID]) FROM SYS.PARTITIONS WHERE hobt_id = 72057594051821568 -- IT WILL GIVE WHICH TABLE IS IT.

SELECT * FROM SYS.PARTITIONS WHERE hobt_id = 72057594051821568 

-- DEADLOCK PREVENTION 

ALTER PROC SP_TRANSACTION1
AS 
BEGIN
    BEGIN TRAN
    BEGIN TRY
        UPDATE TABLEA SET NAME = 'MARK TRANSACTION 1' WHERE ID =1
        WAITFOR DELAY '00:00:10'
        UPDATE TABLEB SET NAME = 'MARK TRANSACTION 1' WHERE ID =1
        COMMIT TRAN
        PRINT 'TRANSACTION SUCESSFUL'
    END TRY
    BEGIN CATCH
        IF(ERROR_NUMBER() = 1205)
        BEGIN 
            SELECT 'ROLLBACK . TRANSACTION IS FAILED , PLEASE TRY'
        END
        ROLLBACK
    END CATCH
END

-- SET DEADLOCK_PRIORITY HIGH
ALTER PROC SP_TRANSACTION2
AS 
BEGIN
    BEGIN TRAN
    BEGIN TRY
        UPDATE TABLEB SET NAME = 'MARY TRANSACTION 2' WHERE ID =1
        WAITFOR DELAY '00:00:10'
        UPDATE TABLEA SET NAME = 'MARY TRANSACTION 2' WHERE ID =1
    COMMIT TRAN
    PRINT 'TRANSACTION SUCCESSFUL'
    END TRY
    BEGIN CATCH
    IF(ERROR_NUMBER() = 1205)
    BEGIN
        SELECT 'DEADLOCK . TRANSACTION IS FAILED . PLEASE TRY LATER'
    END
    ROLLBACK
    END CATCH
END

EXECUTE SP_TRANSACTION2