DECLARE @TARGETNUMBER INT 
SET @TARGETNUMBER = 10
EXECUTE SP_PRINT_EVEN @TARGETNUMBER
PRINT 'DONE'

ALTER PROCEDURE SP_PRINT_EVEN
@TARGETNUMBER INT
AS
BEGIN
    DECLARE @STARTNUMBER INT
    SET @STARTNUMBER = 0
    WHILE (@STARTNUMBER <= @TARGETNUMBER)
    BEGIN
        IF(@STARTNUMBER % 2 = 0)
        BEGIN
            PRINT @STARTNUMBER
        END
        SET @STARTNUMBER = @STARTNUMBER + 1
    END
    PRINT 'FINISHED PRINTING EVEN NUMBER TILL ' + RTRIM(@TARGETNUMBER)
END