SELECT * FROM EMPLOYEE
SELECT * FROM DEPARTMENT

-- USING VIEW
CREATE VIEW VW_COUNTTOTALEMPLOYEE
AS
SELECT DEPARTMENT_ID,DEPARTMENT_NAME,COUNT(*) AS TOTAL_EMPLOYEE FROM EMPLOYEE
JOIN DEPARTMENT ON DEPARTMENT.ID = EMPLOYEE.DEPARTMENT_ID GROUP BY DEPARTMENT_ID, DEPARTMENT_NAME

SELECT * FROM VW_COUNTTOTALEMPLOYEE

-- USING TEMP TABLE 
SELECT DEPARTMENT_ID, DEPARTMENT_NAME , COUNT(*) AS TOTAL_EMPLOYEE INTO #TEMPTABLE FROM EMPLOYEE
JOIN DEPARTMENT ON DEPARTMENT.ID = EMPLOYEE.DEPARTMENT_ID GROUP BY DEPARTMENT_ID,DEPARTMENT_NAME

SELECT * FROM #TEMPTABLE WHERE TOTAL_EMPLOYEE > 3

DROP TABLE #TEMPTABLE

-- USING TABLE VARIABLE

DECLARE @EMPLOYEECOUNT TABLE(DEPARTMENT_ID INT,DEPARTMENT_NAME NVARCHAR(20),TOTAL_EMPLOYEE INT)
INSERT @EMPLOYEECOUNT 
SELECT DEPARTMENT_ID, DEPARTMENT_NAME, COUNT(*) AS TOTAL_EMPLOYEE FROM EMPLOYEE
JOIN DEPARTMENT ON DEPARTMENT.ID = EMPLOYEE.DEPARTMENT_ID GROUP BY DEPARTMENT_ID, DEPARTMENT_NAME

SELECT * FROM @EMPLOYEECOUNT --  TO GET THE VALUE WE MUST RUN THE CMD WITH WHOLE DECLARATION OF TABLE VARIABLE

-- USING DERIVED TABLE(GETTING TABLE FROM ANOTHER TABLE )

SELECT DEPARTMENT_ID,DEPARTMENT_NAME,TOTAL_EMPLOYEE FROM (
    SELECT DEPARTMENT_ID, DEPARTMENT_NAME,COUNT(*) AS TOTAL_EMPLOYEE FROM EMPLOYEE 
    JOIN DEPARTMENT ON DEPARTMENT.ID = EMPLOYEE.DEPARTMENT_ID GROUP BY DEPARTMENT_ID,DEPARTMENT_NAME
) AS EMPLOYEECOUNT

SELECT DEPARTMENT_ID,DEPARTMENT_NAME,TOTAL_EMPLOYEE FROM (
    SELECT DEPARTMENT_ID, DEPARTMENT_NAME,COUNT(*) AS TOTAL_EMPLOYEE FROM EMPLOYEE 
    JOIN DEPARTMENT ON DEPARTMENT.ID = EMPLOYEE.DEPARTMENT_ID GROUP BY DEPARTMENT_ID,DEPARTMENT_NAME
) 
AS EMPLOYEECOUNT WHERE TOTAL_EMPLOYEE>2

-- USING CTE (COMMON TABLE EXPRESSION)

WITH EMPLOYEECOUNT(DEPARTMENT_ID,DEPARTMENT_NAME,TOTAL_EMPLOYEE)  -- CTE START WITH 'WITH KEYWORD FOLLOWED BY VARIABLE NAME'
AS 
(
    SELECT DEPARTMENT_ID, DEPARTMENT_NAME,COUNT(*) AS TOTAL_EMPLOYEE FROM EMPLOYEE
    JOIN DEPARTMENT ON DEPARTMENT.ID = EMPLOYEE.DEPARTMENT_ID GROUP BY DEPARTMENT_ID, DEPARTMENT_NAME
)
-- SELECT * FROM DEPARTMENT     // WHILE EXECUTING CTE THERE WILL BE NO OTHER TASK HAS TO BE RUN WHILE EXECUTING
SELECT * FROM EMPLOYEECOUNT