-- GUID (GLOBAL UNIQUE IDENTIFIER) IT IS 16 BYTE BINARY DATA TYPE THAT IS GLOBALLY UNIQUE

DECLARE @ID UNIQUEIDENTIFIER
SELECT @ID = NEWID()
SELECT @ID as MYGUIDNEWID


Create Database USADB
Go

Use USADB
Go

Create Table USACustomers
(
     ID int primary key identity,
     Name nvarchar(50)
)
Go

Insert Into USACustomers Values ('Tom')
Insert Into USACustomers Values ('Mike')

Select * From USADB.dbo.USACustomers

CREATE DATABASE INDIADB 
GO
USE INDIADB
GO
CREATE TABLE INDIACUSTOMERS1(
    ID INT PRIMARY KEY IDENTITY,
    NAME NVARCHAR(50)
)

INSERT INTO INDIACUSTOMERS1 VALUES('KRISHNA')
INSERT INTO INDIACUSTOMERS1 VALUES('ROHAN')

USE SAMPLEDB
GO

Create Table Customers
(
     ID int primary key,
     Name nvarchar(50)
)

SELECT * FROM Customers
SELECT * FROM USADB.dbo.USACustomers
SELECT * FROM INDIADB.dbo.INDIACUSTOMERS1

SELECT * FROM USADB.dbo.USACustomers
UNION ALL
SELECT * FROM INDIADB.dbo.INDIACUSTOMERS1

INSERT INTO Customers 
SELECT * FROM USADB.dbo.USACustomers
UNION ALL                               -- IT WILL GIVE ERROR PRIMARY KEY VIOLATION 
SELECT * FROM INDIADB.dbo.INDIACUSTOMERS1 

Create Table Customers
(
     ID UNIQUEIDENTIFIER primary key,
     Name nvarchar(50)
)

USE USADB
GO
DROP TABLE USACustomers
CREATE TABLE USACustomers(
    ID UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    Name NVARCHAR(50)
)
Insert Into USACustomers Values (NEWID(),'Tom')
Insert Into USACustomers Values (NEWID(),'Mike')

USE INDIADB
GO
DROP TABLE INDIACUSTOMERS1
CREATE TABLE INDIACUSTOMERS1(
    ID UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    NAME NVARCHAR(50)
)

INSERT INTO INDIACUSTOMERS1 VALUES(NEWID(),'KRISHNA')
INSERT INTO INDIACUSTOMERS1 VALUES(NEWID(),'ROHAN')

SELECT * FROM USADB.dbo.USACustomers
SELECT * FROM INDIADB.dbo.INDIACUSTOMERS1


INSERT INTO Customers 
SELECT * FROM USADB.dbo.USACustomers
UNION ALL                               
SELECT * FROM INDIADB.dbo.INDIACUSTOMERS1 


SELECT * FROM Customers

-- CHECK WHETHER GUID IS NULL OR NOT
DECLARE @MYGUID UNIQUEIDENTIFIER
SET @MYGUID = NEWID()

IF(@MYGUID IS NULL)
PRINT 'GUID IS NULL'
ELSE 
PRINT 'GUID IS NOT NULL'

-- EMPTY GUID
SELECT CAST(CAST(0 AS BINARY)AS uniqueidentifier)
-- OR
SELECT CAST(0x0 AS uniqueidentifier)