SELECT * FROM tblperson1

SET IDENTITY_INSERT tblperson1 ON -- IF WE WANT EXPILICITLY TO ADD THE DATA IN TABLE THEN WE HAVE TO 'ON' THE IDENTITY INSERT

CREATE TABLE tblperson1 (PersonID int NOT NULL PRIMARY KEY, Name NVARCHAR(50) NOT NULL) -- CREATED A TABLE AND ON THE IDENTITY COLUMN GRAPHICALLY

CREATE TABLE tblperson2 (PersonID int NOT NULL IDENTITY(1,1) PRIMARY KEY , Name NVARCHAR(50) NOT NULL) -- CREATED A TABLE AND ON THE IDENTITY COLUMN BY QUERY

INSERT INTO tblperson1 VALUES('krishna') -- NOW WE NEED ONLY TO GIVE NAME IT WIL AUTOMATICALLY COUNT THE PERSON ID 

DELETE FROM tblperson1 -- DELETE WHOLE TABLE DATA

DBCC CHECKIDENT(tblperson1, RESEED,0) -- AFTER DELETING WHOLE DATA WE RESET THE IDENTITY SEED VALUE TO '0'. OTHERWISE IT WILL START WITH PREVIOUS VALUE

DELETE FROM tblperson1 WHERE PersonID = 1 -- IT DELETE PERSONID-1 DATA  