-- INDEX --

-- INDEX ARE MADE TO GET THE DATA QUCIKLIY BECAUSE THE QUERY WILL TAKE MORE TIME 
--BCZ OF FULL SCANNING TABLE WHERE AS INDEX HAVE ADDRESS OF THE ROW AND IT GET THE DATA QUICKLY

SELECT * FROM EMPLOYEE WHERE SALARY >4000 AND SALARY<7000

CREATE INDEX IX_EMPLOYEE_SALARY ON EMPLOYEE (SALARY ASC) -- CREATED A INDEX ON EMPLOYEE TABLE OF SALARY (IT WILL BY DEFAULT NONCLUSTERED)

sp_Helpindex EMPLOYEE -- IT WILL TELL HOW MANY INDEX ARE IN THE TABLE

DROP INDEX EMPLOYEE.IX_EMPLOYEE_SALARY -- IT WILL REMOVE THE INDEXS

-- THE BELOW DROP INDEX WILL GIVE ERROR BECAUSE OF ITS UNIQUESS AND CLUSTERED
DROP INDEX EMPLOYEE.PK__EMPLOYEE__3214EC27342D9E6E -- WHENEVER WE CREATE A PRIMARY KEY IT WILL AUTOMATICALLY CREATE A INDEX OF CLUSTERED AND UNIQUENESS

-- TABLE CAN HAVE ONE CLUSTERED INDEX ONLY WHERE AS NONCLUSTERED CAN BE MORE THAN ONE

CREATE CLUSTERED INDEX IX_EMPLOYEE_GENDER_SALARY ON EMPLOYEE (GENDER DESC , SALARY ASC) --COMPOSITE CLUSTERED INDEX

DROP INDEX EMPLOYEE.IX_EMPLOYEE_GENDER_SALARY

CREATE NONCLUSTERED INDEX IX_EMPLOYEE_NAME ON EMPLOYEE (NAME)

CREATE UNIQUE CLUSTERED INDEX IX_EMPLOYEE_ID ON EMPLOYEE (ID ASC) -- WHEN UINQUE IS INTRODUCED THEN NO DUPLICATE DATA CAN BE INSERT . IF THERE IS ALREADY 
-- DUPLICATE DATA IN TABLE THEN WHILE CREATING A UNIQUE CLUSTERED IT WILL GIVE ERROR
DROP INDEX EMPLOYEE.IX_EMPLOYEE_ID

-- CREATE UNIQUE NONCLUSTERED INDEX IX_FIRST_NAME_LASTNAME ON EMPLOYEE (FIRSTNAME,LASTNAME)

-- ALTER TABLE EMPLOYEE ADD CONSTRAINT UQ_EMPLOYEE_CITY UNIQUE CLUSTERED(CITY)

SELECT * FROM EMPLOYEE