CREATE FUNCTION FN_EMPLOYEEBYGENDER(@GENDER NVARCHAR(10))
RETURNS TABLE
AS
RETURN (SELECT [ID],[NAME],[DATEOFBIRTH],[GENDER],[DEPARTMENT_ID] FROM EMPLOYEE WHERE GENDER = @GENDER)

SELECT * FROM FN_EMPLOYEEBYGENDER('MALE')

-- ONE MAJOR DIFFERENCE BETWEEN THE INLINE VALUED FN AND MULTI STATEMENT FN IS THAT IN INLINE VALUED FN WE CAN UPDATE THE DATA
-- BUT IN MULTI STATEMENT FN WE CANNOT UPDATE THE VALUE OF DATA 

UPDATE FN_EMPLOYEEBYGENDER('MALE') SET NAME='SAM' WHERE NAME ='ANIKET'

SELECT * FROM EMPLOYEE

--BELOW ONE GIVING SOME ERROR AMBIGUOUS COLUMN NAME ID

-- CREATE FUNCTION FN_EMPLOYEEBYGENDER(@GENDER NVARCHAR(10))
-- RETURNS TABLE
-- AS
-- RETURN (SELECT ID,NAME,DATEOFBIRTH,GENDER,DEPARTMENT_NAME FROM EMPLOYEE JOIN DEPARTMENT ON EMPLOYEE.DEPARTMENT_ID = DEPARTMENT.ID)

-- SELECT ID,NAME,DATEOFBIRTH,GENDER,DEPARTMENT_NAME FROM FN_EMPLOYEEBYGENDER('MALE') E JOIN DEPARTMENT D ON  D.ID = E.DEPARTMENT_ID