-- CREATE TABLE EMPLOYEE (
--  ID INT NOT NULL PRIMARY KEY,
--  NAME VARCHAR(25) ,
--  GENDER VARCHAR(25) NOT NULL ,
--  SALARY INT ,
--  DEPARTMENT_ID INT NULL)

-- SELECT * FROM EMPLOYEE 

-- UPDATE EMPLOYEE SET GENDER = 'MALE' WHERE NAME='KRISHNA'

-- INSERT  INTO EMPLOYEE VALUES (8,'VED', 'MALE',5000000,2)

SELECT * FROM EMPLOYEE 

-- CREATE TABLE DEPARTMENT (
--     DEPARTMENT_ID INT NOT NULL PRIMARY KEY,
--     DEPARTMENT_NAME VARCHAR(25) NOT NULL
-- )

-- INSERT INTO DEPARTMENT VALUES(3,'BPO')

-- ALTER TABLE EMPLOYEE ADD CONSTRAINT FK_EMPLOYEE_DEPARTMENT FOREIGN KEY (DEPARTMENT_NAME) REFERENCES  DEPARTMENT(DEPARTMENT_ID)

SELECT * FROM DEPARTMENT

SELECT NAME,GENDER,SALARY,DEPARTMENT_NAME FROM EMPLOYEE         -- IT GIVES INTERSECTION OF BOTH TABLE
INNER JOIN DEPARTMENT ON EMPLOYEE.DEPARTMENT_ID = DEPARTMENT.ID

SELECT NAME, GENDER, SALARY, DEPARTMENT_NAME FROM EMPLOYEE     -- IT GIVES LEFT TABLE 
LEFT OUTER JOIN DEPARTMENT ON EMPLOYEE.DEPARTMENT_ID = DEPARTMENT.ID

SELECT NAME, GENDER, SALARY, DEPARTMENT_NAME FROM EMPLOYEE    -- IT GIVES RIGHT TABLE
RIGHT OUTER JOIN DEPARTMENT ON EMPLOYEE.DEPARTMENT_ID = DEPARTMENT.ID

SELECT NAME, GENDER, SALARY, DEPARTMENT_NAME FROM EMPLOYEE    -- IT GIVES SUMMATION OF BOTH LEFT AND RIGHT TABLE
FULL JOIN DEPARTMENT ON EMPLOYEE.DEPARTMENT_ID = DEPARTMENT.ID

SELECT NAME, GENDER, SALARY, DEPARTMENT_NAME FROM EMPLOYEE    -- IT GIVES CROSS PRODUCT OF BOTH TABLE
CROSS JOIN DEPARTMENT

------------------------------------- ADVANCE OR INTELLIGENT JOIN ------------------------------------------

SELECT NAME, GENDER, SALARY, DEPARTMENT_NAME FROM EMPLOYEE
LEFT JOIN DEPARTMENT ON EMPLOYEE.DEPARTMENT_ID = DEPARTMENT.ID WHERE DEPARTMENT_ID IS NULL

SELECT NAME, GENDER, SALARY, DEPARTMENT_NAME FROM EMPLOYEE
RIGHT JOIN DEPARTMENT ON EMPLOYEE.DEPARTMENT_ID = DEPARTMENT.ID WHERE EMPLOYEE.DEPARTMENT_ID IS NULL

SELECT NAME, GENDER, SALARY, DEPARTMENT_NAME FROM EMPLOYEE
FULL JOIN DEPARTMENT ON EMPLOYEE.DEPARTMENT_ID = DEPARTMENT.ID WHERE EMPLOYEE.DEPARTMENT_ID IS NULL OR DEPARTMENT.ID IS NULL