CREATE FUNCTION FN_MSTVF_GETEMPLOYEE()
RETURNS @TABLE TABLE (ID INT , NAME NVARCHAR(20), DOB DATE)
AS 
BEGIN
    INSERT INTO @TABLE
    SELECT ID,NAME,CAST(DATEOFBIRTH AS DATE) FROM EMPLOYEE
    RETURN
END

SELECT * FROM FN_MSTVF_GETEMPLOYEE()

-- ONE MAJOR DIFFERENCE BETWEEN THE INLINE VALUED FN AND MULTI STATEMENT FN IS THAT IN INLINE VALUED FN WE CAN UPDATE THE DATA
-- BUT IN MULTI STATEMENT FN WE CANNOT UPDATE THE VALUE OF DATA 

UPDATE FN_MSTVF_GETEMPLOYEE() SET NAME='SAM1' WHERE NAME ='ANIKET'