--USER 1
-- CREATE TABLE Test1(
--     ID int identity(1,1),
--     Value nvarchar(50)
-- )

-- CREATE TABLE Test2(
--     ID int IDENTITY(1,1),
--     Value NVARCHAR(50)
-- )
SELECT * FROM Test1
SELECT * FROM Test2
INSERT INTO Test1 VALUES('X')
CREATE TRIGGER trForInsert ON Test1 FOR INSERT -- CREATED A TRIGGER FUNCTION WHENEVER WE INSERT IN TABLE TEST1 THEN IT WILL PERFORM SOME TASK
AS 
BEGIN -- PERFORMING OF TASK START FROM HERE 
    INSERT INTO Test2 VALUES('YYYY')
END -- END IT HERE
SELECT SCOPE_IDENTITY() -- IT RETRIVE THE LAST IDENTITY COLUMN VALUE IN SAME SESSION  AND SAME SCOPE
SELECT @@IDENTITY -- IT GIVE THE VALUE OF SAME SESSION BUT  ACROSS ANY SCOPE 
SELECT IDENT_CURRENT('Test2') -- IT GIVE THE VALUE OF ANY SESSION AND ANY SCOPE

