-- SCALAR USER DEFINE FUNCTION (SCALAR UDF)

--SYNTAX IS GIVEN BELOW
-- CREATE FUNCTION FUNCTION_NAME(PARAMETER)
-- RETURNS DATATYPE
-- AS
-- BEGIN
--     STATEMENT
--     RETURN RETURNS_DATATYPE
-- END

CREATE FUNCTION AGE(@DOB DATE)
RETURNS INT
AS
BEGIN
    DECLARE @AGE INT
    SET @AGE = DATEDIFF(YEAR,@DOB,GETDATE())-
    CASE
        WHEN(MONTH(@DOB)>MONTH(GETDATE())) OR (MONTH(@DOB) = MONTH(GETDATE()) AND DAY(@DOB)>DAY(GETDATE()))
        THEN 1 ELSE 0
    END
    RETURN @AGE
END

SELECT [ID],[NAME],[DATEOFBIRTH],dbo.AGE(DATEOFBIRTH) AS AGE FROM tblEMPLOYEEDOB

SELECT [ID],[NAME],[DATEOFBIRTH],dbo.AGE(DATEOFBIRTH) AS AGE FROM tblEMPLOYEEDOB WHERE dbo.AGE(DATEOFBIRTH)>30

-- DROP FUNCTION DBO.AGE  // IT WILL DELETE THE AGE FUNCTION