-- SELECT * FROM EMPLOYEE

-- DROP TABLE EMPLOYEE

CREATE FUNCTION FN_GETEMPLOYEEBYID(@ID INT)
RETURNS NVARCHAR(30)
BEGIN
    RETURN (SELECT NAME FROM EMPLOYEE WHERE ID = @ID)
END

-- APPLYING SCHEMA BINDING 

ALTER FUNCTION FN_GETEMPLOYEEBYID(@ID INT)
RETURNS NVARCHAR(30)
WITH SCHEMABINDING
AS
BEGIN
    RETURN (SELECT NAME FROM dbo.EMPLOYEE WHERE ID = @ID) -- FOR SCHEMA BINDING WE HAVE TO GIVE OWNER NAME ALSO dbo.table_name OTHERWISE IT WILL GIVE ERROR
END

SELECT dbo.FN_GETEMPLOYEEBYID(2)

-- AFTER APPLYING A SCHEMA BINDING IF NOW WE TRY TO DELETE A EMPLOYEE TABLE IT WILL NOT GOING TO DELETE IT . IF WE HAVE NOT APPLIED A SCHEMA
-- BINDING THE IT WILL DELETE THE TABLE

DROP TABLE EMPLOYEE  -- Cannot DROP TABLE 'EMPLOYEE' because it is being referenced by object 'FN_GETEMPLOYEEBYID'

sp_helptext FN_GETEMPLOYEEBYID