SELECT [ID],[NAME],[EMAIL],[GENDER_ID],[AGE],[CITY] FROM tblperson -- IT WILL SHOW ALL COLUMN LIST WHICH IS SPECIFIED 

SELECT * FROM tblperson -- IF WE WANT TO DISPLAY ALL THE COLUMN LIST THEN WE CAN DEFINE * IN PLCAE OF COLUMN LIST BUT ITS BETTER TO DEFINE A COLUMN LIST

SELECT DISTINCT CITY FROM tblperson -- it will display all the city present in table once

SELECT DISTINCT [NAME],[CITY] FROM tblperson -- IT WILL DISTINCT BETWEEN TWO COLUMN ONLY NAME AND CITY

SELECT * FROM tblperson WHERE CITY = 'VARANASI' -- IT WILL GIVE THOSE DATA WHICH HAVE CITY VARANASI ONLY

SELECT * FROM tblperson WHERE CITY <> 'VARANASI' --IT WILL GIVE THOSE DATA WHICH DOESN'T HAVE CITY VARANASI. WE CAN USE  != ALSO INSTEAD OF <>

SELECT * FROM tblperson WHERE AGE > 19 AND AGE <=25  --IT WILL GIVE THOSE DATA WHICH SATISFIES THIS CONDITION ONLY.

SELECT * FROM tblperson WHERE AGE IN (20,21,25) --IT WILL GIVE THOSE DATA WHICH IS PRESENT IN THE LIST

SELECT * FROM tblperson WHERE AGE BETWEEN 19 AND 25 -- IT WILL GIVE 19 , 25 AND ALL THE NO. WHICH LIES IN BETWEEN

SELECT * FROM tblperson WHERE EMAIL LIKE '%@K%' -- % MEANS ANY CHARCHATER 

SELECT * FROM tblperson WHERE EMAIL LIKE '%@%' 

SELECT * FROM tblperson WHERE EMAIL NOT LIKE '%@%'

SELECT * FROM tblperson WHERE EMAIL LIKE '_@_.com' -- _ MEANS ONLY ONE CHARCHATER

SELECT * FROM tblperson WHERE [NAME] LIKE '[^KTM]%' -- [] MEANS STARTING OF CHARCHATER WILL BE FROM HERE

SELECT * FROM tblperson WHERE (CITY = 'VARANASI' OR CITY = 'NEW DELHI') AND AGE>= 20 -- IT IS MULTIPLE CONDITIONS 

SELECT * FROM tblperson ORDER BY [NAME] DESC -- IT CHANGE THE ORDER OF DATA IN DESCENDING ORDER 

SELECT * FROM tblperson ORDER BY [NAME] DESC , AGE ASC

SELECT TOP 3 * FROM tblperson -- IT WILL SHOW TOP 3 DATA 

SELECT TOP 50 PERCENT * FROM tblperson

SELECT TOP 1 * FROM tblperson ORDER BY AGE DESC -- IT WILL TOP MOST ELDER PERSON PRESENT IN DATA

-- INSERT INTO tblperson VALUES (7,'MARY','M@M.COM',1,21,'LONDON')