-- CREATE DATABASE Sample4
-- ALTER DATABASE Sample1 MODIFY NAME = KRISHNA
-- sp_renamedb 'NEW','KRISHNA'
-- ALTER DATABASE KRISHNA SET SINGLE_USER WITH ROLLBACK IMMEDIATE
-- DROP DATABASE KRISHNA 

-- ALTER DATABASE SAMPLE SET SINGLE_USER WITH ROLLBACK IMMEDIATE
-- DROP DATABASE SAMPLE
