SELECT * FROM EMPLOYEE

SELECT ASCII('A') AS CHARACTERINDEX  -- IT GIVE ASCII CODE OF CHARACTER . IF THERE IS MORE THAN ONE CHARACTER THEN IT WILL GIVE ASCII OF FIRST CHARACTER ONLY

SELECT CHAR(65) AS CHARACTER

-- PRINTING OF ALPHABET FROM A-Z USING WHILE LOOP
DECLARE @START INT  -- DECLARING A VARAIABLE WITH THE NAME START
SET @START = 65 -- INITILAZING THE START VARIABLE USING SET KEYWORD
WHILE(@START <= 90) 
BEGIN
    PRINT CHAR(@START)
    SET @START = @START + 1 -- INCREMENTING THE VALUE OF START
END

-- CREATE TABLE EMPLOYEES (
--     ID INT NOT NULL PRIMARY KEY,
--     [FIRSTNAME] NVARCHAR(50) NULL,
--     [MIDDLENAME] NVARCHAR(50) NULL,
--     [LASTNAME] NVARCHAR(50) NULL,
--     [EMAIL] NVARCHAR(50),
--     [GENDER] NVARCHAR(50),
--     [DEPARTMENTID] INT NOT NULL,
--     [NUMBER] INT
-- )
SELECT * FROM EMPLOYEES
-- INSERT INTO EMPLOYEES VALUES(8,'  KRISHNA  ','KANT','MAURYA','KKK@GMAIL.COM','MALE',1,2)

SELECT LTRIM('  KRISHNA') -- IT WILL REMOVE A BLANK SPACE PRESENT IN LEFT SIDE
SELECT RTRIM('KRISHNA      ') -- IT WILL REMOVE A BLANK SPACE PRESENT IN RIGHT SIDE
SELECT LTRIM(RTRIM(FIRSTNAME)) AS [FIRSTNAME],[MIDDLENAME], LTRIM(RTRIM(LASTNAME)) AS [LASTNAME], LOWER(LTRIM(RTRIM(FIRSTNAME)))+ ' ' + LOWER(MIDDLENAME) + ' ' + LOWER(LASTNAME) AS FULLNAME FROM EMPLOYEES

SELECT LOWER('KRISHNA') -- IT WILL WRITE IN LOWER CASE
SELECT UPPER('krishna') -- IT WILL WRITE IN UPPER CASE
SELECT REVERSE('KRISHNA KANT MAURYA') -- IT WILL REVERSE THE STRING
SELECT LEN('KRISHNA KANT MAURYA') -- IT WILL COUNT THE CHARACHTER AND BLANK SPACE BETWEEN THE WORD. IN THE LAST END OF THE WORD IF THERE IS BLANK SPACE THEN IT WILL NOT GOING TO COUNT THAT SPACE

SELECT LEFT('KRISHNA KANT',4) -- IT WILL TAKE TWO PARAMETER ONE IS EXPRESSION AND OTHER IS LENGTH . IT WILL GIVE THAT MUCH OF CHARACTER FROM LEFT SIDE 
SELECT RIGHT('KRISHNA KANT',6) -- IT WILL ALSO TAKE TWO PARAMETER LIKE ABOVE ONE. IT WILL GIVE THAT MUCH OF CHARACTER FROM RIGHT SIDE.
SELECT CHARINDEX('.','KKM@GMAIL.COM',0) -- IT WILL TAKE THREE PARAMETER , IT EILL GIVE THE INDEX OF THAT EXPRESSION WHICH WE ARE SEARCHING

SELECT SUBSTRING('KRISHNA@GMAIL.COM',3,5) -- IT WILL GIVE SUBSTRING 

SELECT * FROM EMPLOYEES

SELECT SUBSTRING(EMAIL,CHARINDEX('@',EMAIL)+1,LEN(EMAIL)-CHARINDEX('@',EMAIL)) AS EMAILDOMAIN, COUNT(ID) AS TOTAL FROM EMPLOYEES 
GROUP BY SUBSTRING(EMAIL,CHARINDEX('@',EMAIL)+1,LEN(EMAIL)-CHARINDEX('@',EMAIL)) 

SELECT REPLICATE('*',3) -- IT WILL MAKE COPY/DUPLICATE OF GIVEN EXPRESSION

SELECT LTRIM(RTRIM(FIRSTNAME)) AS FIRSTNAME,LASTNAME ,
SUBSTRING(EMAIL,1,2) + REPLICATE('*',5) + SUBSTRING(EMAIL,CHARINDEX('@',EMAIL),LEN(EMAIL)-CHARINDEX('@',EMAIL)+1) AS EMAIL
FROM EMPLOYEES

-- SPACE(10) THIS FUNCTION WILL PLACE THE 10 BLANK SPACE
SELECT LTRIM(RTRIM(FIRSTNAME)) + SPACE(3) + LTRIM(RTRIM(LASTNAME)) AS FULLNAME FROM EMPLOYEES

SELECT PATINDEX('%@GMAIL.COM','KKM@GMAIL.COM') -- IT GIVE THE FIRST OCCURENCE OF PATTERN IF FOUND THEN IT WILL GIVE INDEX OTHERWISE IT WILL RETURN ZERO

SELECT EMAIL,PATINDEX('%@AAA.COM',EMAIL) AS EMAIL FROM EMPLOYEES WHERE PATINDEX('%@AAA.COM',EMAIL)>0

SELECT REPLACE('KRISHNA@GMAIL.COM','.COM','.NET') -- IT REPLCAE THE VALUE

SELECT EMAIL, REPLACE(EMAIL,'.COM','.NET') AS CONVERTEDEMAIL FROM EMPLOYEES

SELECT STUFF('KKMK@GMAIL.COM',2,3,'****') -- IT INSERT THE REPLACEMENT EXPRESSION FROM STARTING POSITION TILL THE NO. OF CHAR 