-- STRUCTURE OF TABLE
CREATE TYPE EMPTABLETYPE AS TABLE(
    ID INT PRIMARY KEY,
    NAME NVARCHAR(50),
    GENDER NVARCHAR(10)
)
-- TABLE IN WHICH VALUE IS TO BE PASSED AS PARAMETER
Create Table EMPLOYEEBACKUP2
(
    Id int primary key,
    Name nvarchar(50),
    Gender nvarchar(10)
)

-- STORED PROCEDURE TO INSERT THE DATA INTO EMPLOYEEBACKUP2 FROM @EMPLOYEETYPE
CREATE PROC SP_INSERTEMPLOYEE
@EMPTABLETYPE EMPTABLETYPE READONLY
AS
BEGIN
    INSERT INTO EMPLOYEEBACKUP2 SELECT * FROM @EMPTABLETYPE
END


DECLARE @EmployeeTableType EMPTABLETYPE -- DECLARING A EMPTABLETYPE TABLE BASICALLY WE ARE CREATING A TABLE NOW BEFORE THAT WAS STRUCTURE

INSERT INTO @EmployeeTableType VALUES (1, 'Mark', 'Male')
INSERT INTO @EmployeeTableType VALUES (2, 'Mary', 'Female')
INSERT INTO @EmployeeTableType VALUES (3, 'John', 'Male')
INSERT INTO @EmployeeTableType VALUES (4, 'Sara', 'Female')
INSERT INTO @EmployeeTableType VALUES (5, 'Rob', 'Male')

EXECUTE SP_INSERTEMPLOYEE @EmployeeTableType

SELECT * FROM EMPLOYEEBACKUP2