-- Transaction must follow ACID(ATOMICITY, CONSISTENT, ISOLATION, DURABILITY) PROPERTY

-- TRANSACTION MUST FOLLOW STEP
-- BEGIN TRANSACTION
-- PROCESS DATABASE COMMAND
-- CHECK ERROR IF OCCURED ROLLBACK  TRANSACTION
-- ELSE COMMIT TRANSACTION

-- CREATE TABLE PHYSICALADDRESS(
--     ADDRESSID INT PRIMARY KEY,
--     EMPLOYEENUMBER INT,
--     HOUSENUMBER INT,
--     STREETADDRESS NVARCHAR(10),
--     CITY NVARCHAR(10),
--     POSTALCODE NVARCHAR(10)
-- )
-- CREATE TABLE MAILINGADDRESS(
--     ADDRESSID INT PRIMARY KEY,
--     EMPLOYEENUMBER INT,
--     HOUSENUMBER INT,
--     STREETADDRESS NVARCHAR(10),
--     CITY NVARCHAR(10),
--     POSTALCODE NVARCHAR(10)
-- )
INSERT INTO PHYSICALADDRESS VALUES(1,101,10,'KINGSTREET','LONDOON','CR27DW')
INSERT INTO MAILINGADDRESS VALUES(1,101,10,'KINGSTREET','LONDOON','CR27DW')

SELECT * FROM PHYSICALADDRESS
SELECT * FROM MAILINGADDRESS

CREATE PROCEDURE SP_UPDATEADDRESS
AS 
BEGIN
    BEGIN TRY
        BEGIN TRANSACTION
            UPDATE MAILINGADDRESS SET CITY = 'LONDON' WHERE ADDRESSID = 1 AND EMPLOYEENUMBER = 101
            UPDATE PHYSICALADDRESS SET CITY = 'LONDON' WHERE ADDRESSID = 1 AND EMPLOYEENUMBER = 101
        COMMIT TRANSACTION
        PRINT 'TRANSACTION COMMITED'
    END TRY
    BEGIN CATCH
        ROLLBACK TRANSACTION
        PRINT 'TRANSACTION ROLLBACK'
    END CATCH
END
EXEC SP_UPDATEADDRESS

