-- CREATE TABLE INDIACUSTOMERS(
--     ID INT NOT NULL PRIMARY KEY,
--     NAME NVARCHAR(50),
--     EMAIL NVARCHAR(50)
-- )
-- CREATE TABLE UKCUSTOMERS(
--     ID INT NOT NULL PRIMARY KEY,
--     NAME NVARCHAR(50),
--     EMAIL NVARCHAR(50)
-- )
-- CREATE TABLE USCUSTOMERS(
--     ID INT NOT NULL PRIMARY KEY,
--     NAME NVARCHAR(50),
--     EMAIL NVARCHAR(50)
-- )

SELECT * FROM INDIACUSTOMERS
SELECT * FROM UKCUSTOMERS
SELECT * FROM USCUSTOMERS
-- INSERT INTO USCUSTOMERS VALUES(2,'TODD','T@T.COM')

SELECT * FROM INDIACUSTOMERS
UNION  -- IT COMBINE THE TWO TABLE OR MORE AND REMOVE THE DUPLICATE DATA
SELECT * FROM UKCUSTOMERS

SELECT * FROM INDIACUSTOMERS
UNION ALL -- IT COMBINE THE TWO TABLE OR MORE AND DID NOT REMOVE THE DUPLICATE DATA
SELECT * FROM UKCUSTOMERS

SELECT * FROM INDIACUSTOMERS
UNION 
SELECT * FROM USCUSTOMERS

-- IT IS DIFFERENT FROM JOINS BECAUSE IT COMBINE THE TABLE IN HORIZONTAL FORM AND IN JOINS IT COMBINE TWO TABLE IN VERTICAL FORM

SELECT * FROM INDIACUSTOMERS
UNION ALL
SELECT * FROM UKCUSTOMERS
UNION ALL
SELECT * FROM USCUSTOMERS
ORDER BY NAME