SELECT * FROM tblperson

DELETE tblperson

ALTER TABLE tblperson ADD CONSTRAINT UQ_tblperson_MAIL UNIQUE (EMAIL) -- ADDED A UNIQUE KEY CONSTRAINT IT CAN HAVE NULL VALUE BUT PRIMARY KEY DOESN'T HAVE NULL VALUE
-- IT PREVENT FROM ENTERING A DUPLICATE DATA

INSERT INTO tblperson VALUES(2,'SHUBHAM','K@K.COM',1,20)

ALTER TABLE tblperson DROP CONSTRAINT UQ_tblperson_MAIL -- DROP/REMOVED THE UNIQUE KEY CONSTRAINT